language: python

python:
  - "3.5"
  - "3.6"

install:
  - pip install -r requirements.txt
  - pip install -r requirements-dev.txt
  - pip install codecov

script:
  - pytest . -v --cov=.

after_success:
  - codecov