language: python

python:
  - "3.5"
  - "3.6"

install:
  - pip install -r requirements.txt
  - pip install -r requirements-dev.txt
  - pip install codecov coveralls

script:
  - pytest . -v --cov=.

after_success:
  - codecov
  - coveralls

deploy:
  provider: pypi
  user: $PYPI_USERNAME
  password: $PYPI_PASSWORD
  on:
    python: "3.5"
    tags: true
